Sprint 12
DemidenGo/ImageFeed pull request #5
Opened 2023-01-11 14:00 UTC by DemidenGo

Sprint 12 task is done by Yuriy Demidenko

2023-01-12 14:43 UTC, IBDesignable requested changes

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Helpers/URLRequest+Extensions.swift
> +        var fullURL = component != nil ? url.appendingPathComponent(component!) : url
предпочтительно использовать if let, вместо проверок на nil вместе с force unwrap

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        photoImageView.kf.cancelDownloadTask()
ячейки переиспользуются, поэтому здесь не только сбрасывать загрузку изображения, но и предыдущий стейт сбросить: обнулить картинку, текст, лайк

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                UIBlockingProgressHUD.dismiss()
Это не будет работать. 

Ячейки сейчас не сбрасывают стейт у картинки, и ты можешь после обновления моделей свитчнуть не на ту картинку. 

Нужно прям передвать буль конкретной обновленной ячейки. Так ты гаранитруешь что модель = отображению. Здесь же код полается на последовательность вызовов, которую ты предполагал, а  на деле последовательность получается иная :) 

Попробуй налайкать 10ю ячеку и посмотреть как лайк у нее при скроле сохраняется. 

Алгоритм такой:
1 кнопка нажата
2 ушел запрос на обнолвение с запрашиваемым стейтом
3 получаем ответ от сервера
4 обновляем хранилище моделей (фото и его лайк)
5 возвращаем стейт запрашиваемой ячейки
6 обновляем отображение по индексу этой ячейки

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +    var delegate: ProfileViewControllerDelegate?
Сильная ссылка уместна? можешь рассказать почему?

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                    self.photos[index].isLiked.toggle()
я бы не использовала здесь тогл, так как это не совсем предсказуемая штука. Ты же не блокируешь повторные запросы здесь. Лучше присвоить то что запрашивали isLike.

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +        }
первый запрос:
lastLoadedPage = 0
nextPage = lastLoadedPage + 1 

fetchNextPageOfPhotos запросит страницу по индексу 1 (nextPage = 1)
по окончанию запроса, lastLoadedPage будет равна 1.

Дальше пагинация будет вполне верной. Но давай уточним, точно ли индексация с единицы? обычно все-таки с нуля

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                                          largeImageURL: photoResult.urls.full,
можно вынести мапинг в отдельное расширение, и тогда здесь читаемость повысится

```
extension PhotoResult {
func convertToViewModel() -> Photo { ...
}
}

```

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                                          largeImageURL: photoResult.urls.full,
плюс можно будет использовать функциональное программирование:
jsonResponse.map { $0. convertToViewModel() } - который вернет сразу массив с фото, останется только положить его в конец пачкой

2023-01-12 14:43 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        likeButton.setImage(likeNoActiveImage, for: .normal)
давай сюда добавим параметр, чтобы не заниматься сравнением иконок

2023-01-13 10:58 UTC, DemidenGo commented on ImageFeed/Profile/ProfileViewController.swift
> +    var delegate: ProfileViewControllerDelegate?
Здесь делегат у меня SplashViewController, у него нет ссылки на ProfileViewController. Если сделать ссылку слабой, то делегат будет деинититься ещё до обращения к нему и, соответственно, функцию свою выполнять не будет.

2023-01-13 11:24 UTC, DemidenGo commented on ImageFeed/Services/ImagesListService.swift
> +        }
Так пагинация у unsplash начинается с единицы. Если я сделаю пагинацию с нуля, то получу две одинаковые первые страницы. То есть на запрос с page = 0 unsplash мне выдаст первую страницу и на запрос с page = 1 unsplash мне выдаст первую страницу. Два первых запроса вернут одинаковый результат.

2023-01-14 15:55 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +        }
Спасибо, так понятнее :) у всех сервисов по разному!

2023-01-14 16:10 UTC, IBDesignable approved these changes
Предлагаю поправить только лишний setImage во вью контроллере на setIsLiked, остальное все принято! Сильная работа, давай в том же духе дальше :)

2023-01-14 16:10 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +    var delegate: ProfileViewControllerDelegate?
Интересно. Хорошо, что делегат не дает знаний о том что это конкретный SplashViewController, тут принципы не нарушены. Не могу сформулировать сейчас почему это плохо, учитывая что сейчас не достаточно архитектурных знаний чтобы разрулить это место, поэтому можешь оставить как есть. 

Однако обычно при разлогине меняют рут вью контроллер на начальный, при этом начальный вполне уместно пересоздать, а не хранить и использовать его на протяжении всей жизни приложения. Сейчас это легковесный экран и таскать его повсюду вроде бы ок. Но просто представь, что у тебя первый экран содержит видео и подгрузил для этого много ресурсов. И удерживать его в памяти не ок был было.

2023-01-14 16:10 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            loadedPhoto.isLiked ? cell.likeActiveImage : cell.likeNoActiveImage, for: .normal)
вот здесь бы likeButton закрыть private (обычно так и делают) и использовать cell.setIsLiked(loadedPhoto.isLiked)

2023-01-14 16:10 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            loadedPhoto.isLiked ? cell.likeActiveImage : cell.likeNoActiveImage, for: .normal)
Ну и есть прям совсем "как в проде": то обычно формируют специальную вью модель, и передают ее на ячейку. 

То есть для того чтобы ячейку настроить нам нужна картинка, лайк и дата. Причем все данные должны быть приведены в нужный формат: дата в строку, каритинка в URL или UIImage. 
и configure(with viewModel: ..) вызывают на ячейке.

Этот же метод во вью контроллере получает слишком много доступа к элементам ячейки, и ему бы данные только готовить, а настройку отдать ячейке.

Возможно я ворчу :) в целом можно и ячейку полностью глупенькой оставить.

2023-01-14 16:10 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
>      private var nextPage: UInt { lastLoadedPage + 1 }
все ок, спасибо за коммент

поняла идею, коммент можно из кода убрать

2023-01-15 12:46 UTC, merged